package com.example.mobilecomputing

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.Image
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.Card
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import com.example.mobilecomputing.ui.theme.MobileComputingTheme

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        //This defines the visual appearance of the mobile application.
        setContent {
            MobileComputingTheme {
                ApplicationNavigation()
            }
        }
    }
}
//This handles all the navigation of the application
@Composable
fun ApplicationNavigation(){
    val navController = rememberNavController()
    //This defines all the possible views in the application and navigation between them.
    // Home defines the firts page.
    NavHost(navController = navController, startDestination = "Hippo"){
        //this names the view.
        composable(route = "Hippo"){
            HippoScreen(onHippoClick = {navController.navigate(route="conversation")})
        }

        composable(route = "conversation"){
            Conversation(messages = SampleData.conversationSample, onBack = {navController.popBackStack()})

        }
    }
}
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun HippoScreen(onHippoClick: () -> Unit) {
    //This defines the structure of the view.
    Scaffold(
        topBar = {
            TopAppBar(
                title = {Text(text = "Hippo View")},
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = Color.Magenta,
                    titleContentColor = Color.Black
                )
            )
        }
        //This tells where the elemetns should go.
    ) {  innerPadding ->

        Column(
            modifier = Modifier.padding(innerPadding).fillMaxSize(),
            //This aligns the elements to the middle of the screen.
            verticalArrangement = Arrangement.Center,
            horizontalAlignment = Alignment.CenterHorizontally

        ) {
            //This shows the hippopicture which is clicable.
            Image(
                painter = painterResource(R.drawable.hippo_profile),
                contentDescription =  "Contact profile picture",
                modifier = Modifier
                    .size(240.dp)
                    .clip(CircleShape)
                    .clickable{onHippoClick()

                    }
            )

        }
    }

}

data class Message(val author: String, val body: String)
@Composable
fun MessageCard(msg: Message) {
    var isExpanded by remember { mutableStateOf(false) }
    Card(
        modifier = Modifier
            .padding(all = 8.dp)
            // This makes the card clickable.
            .clickable { isExpanded = !isExpanded }
        ){
        Row {
            //This shows the profile picture.The hippo-picture is generated by using Gemini AI.
            Image(
                painter = painterResource(R.drawable.hippo_profile),
                contentDescription =  "Contact profile picture",
                modifier = Modifier
                    .size(80.dp)
                    .clip(CircleShape)
            )
            Spacer(modifier = Modifier.width(16.dp))

            Column {

                Spacer(modifier = Modifier.height(8.dp))
                //This creates the text element for the author.
                Text(
                    text = msg.author,
                    color = Color.Black,
                    style = TextStyle(
                        fontSize = 20.sp,
                        fontWeight = FontWeight.Bold
                    )
                )
                Spacer(modifier = Modifier.height(4.dp))
                // This creates the text element for the message.
                Text(
                    text = msg.body,
                    color = Color (0xFFB39DDB),
                    style = TextStyle(
                        fontSize = 16.sp,
                        fontWeight = FontWeight.Medium
                    ),
                    maxLines = if (isExpanded) Int.MAX_VALUE else 1
                )
            }
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun Conversation(messages: List<Message>, onBack:() ->Unit) {
    //This defines the structure of the view.
    Scaffold(
        //This is the navigation element which is on top of the page.
        topBar = {
            TopAppBar(
                title = {Text(text = "Hippo View")},
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = Color.Magenta,
                    titleContentColor = Color.Black
                ),
                navigationIcon = {
                    //This is the back arrow button
                    IconButton(onClick = onBack) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Back"
                        )
                    }
                }
            )
        }
        //This tells where the elemetns should go.
    ) { innerPadding ->
        LazyColumn(modifier = Modifier.padding(innerPadding).fillMaxSize(),) {
            //This creates a scrollable list of messages.
            items(messages) { message ->
                MessageCard(message)
            }
        }
    }
}


